name: store_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.5+1

  # Routing
  go_router: ^16.2.2

  # HTTP client
  dio: ^5.9.0

  # Local storage
  shared_preferences: ^2.5.3

  # Speech
  speech_to_text: ^7.3.0

  # Permission handler (Flutter 3+ va Android/iOS)
  permission_handler: ^12.0.1

  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
